/*
 * stub generated by Xtext
 * added code to customise lexer
 */
package com.euclideanspace.aldor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EditorRuntimeModule extends com.euclideanspace.aldor.AbstractEditorRuntimeModule {
	
	/*
	 * I want to customise the lexer.
	 * I have created CustomLexer.java to extend
     * com.euclideanspace.aldor.parser.antlr.internal.InternalEditorLexer.java
	 * but I can't work out how to bind it.
	 * AbstractEditorRuntimeModule seems to contain 3 methods that involve the lexer:
	 * - bindLexer()
	 * - provideInternalEditorLexer()
	 * - configureRuntimeLexer(binder)
	 * I would like to override these in EditorRuntimeModule but I can't change the return type
	 * of provideInternalEditorLexer() in an override.
	 */

	
	// The following causes runtime errors: Failed to create injector for com.euclideanspace.aldor.Editor
	// contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
	@Override
	public Class<? extends org.eclipse.xtext.parser.antlr.Lexer> bindLexer() {
		return com.euclideanspace.aldor.CustomLexer.class;
	}

	// contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
	//@Override
	public com.google.inject.Provider<com.euclideanspace.aldor.CustomLexer>
	                             provideInternalCustomEditorLexer() {
	  return org.eclipse.xtext.parser.antlr.LexerProvider.create(
	    com.euclideanspace.aldor.CustomLexer.class);
	}

	// The following causes runtime errors: Failed to create injector for com.euclideanspace.aldor.Editor
	// contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
	@Override
	public void configureRuntimeLexer(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.parser.antlr.Lexer.class).annotatedWith(
	    com.google.inject.name.Names.named(
	      org.eclipse.xtext.parser.antlr.LexerBindings.RUNTIME
	    )
	  ).to(com.euclideanspace.aldor.CustomLexer.class);
	}
	
	// contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
	/*
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {
		return com.euclideanspace.aldor.parser.antlr.EditorParser.class;
	}
*/
}
