/*
* generated by Xtext
*/
package com.euclideanspace.spad.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/euclideanspace/spad/parser/antlr/internal/InternalEditor.tokens");
	}
}
