/*
* generated by Xtext
*/
package com.euclideanspace.spad.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.euclideanspace.spad.services.EditorGrammarAccess;

public class EditorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EditorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected com.euclideanspace.spad.parser.antlr.internal.InternalEditorParser createParser(XtextTokenStream stream) {
		return new com.euclideanspace.spad.parser.antlr.internal.InternalEditorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
