/*
* generated by Xtext
*/
package com.euclideanspace.euclid.ui.contentassist;

import com.euclideanspace.euclid.ui.contentassist.AbstractEditorProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EditorProposalProvider extends AbstractEditorProposalProvider {

}
