/*
* generated by Xtext
*/
package com.euclideanspace.aldor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/euclideanspace/aldor/parser/antlr/internal/InternalEditor.tokens");
	}
}
