/*
* generated by Xtext
*/
package com.euclideanspace.euclid.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EditorOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
