/*
 * generated by Xtext
 */
package com.euclideanspace.aldor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EditorUiModule extends com.euclideanspace.aldor.ui.AbstractEditorUiModule {
	public EditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
