/*
 * generated by Xtext
 */
package com.euclideanspace.euclid.ui.contentassist

import com.euclideanspace.euclid.ui.contentassist.AbstractEditorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EditorProposalProvider extends AbstractEditorProposalProvider {
}
